apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-html-app
  template:
    metadata:
      labels:
        app: my-html-app
    spec:
      containers:
      - name: web-app
        image: devopsregistersaif2.azurecr.io/mywebapp:${{ github.sha }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-html-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-html-app